# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-04-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20160410_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pending_reason',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
