# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-04-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20160410_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pending_reason',
            field=models.CharField(default='not paid yet', max_length=200),
        ),
    ]
