# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-04-15 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20160410_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
