# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-04-27 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_bad_requests_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad_requests',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
