# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_bad_requests_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
    ]
