# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_orders_partner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='partner_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='partner_hash_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
