# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_auto_20160513_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='partner_hash_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
